FROM --platform=linux/arm64 ubuntu:latest

# Set non-interactive frontend and working directory
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install base system packages
RUN apt-get update && apt-get upgrade -y && \
  apt-get install -y \
  wget \
  sudo \
  gnupg \
  software-properties-common \
  curl \
  unzip && \
  # Clean up
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Use bash shell and source profile
SHELL ["/bin/bash", "-c"]
RUN source ~/.bashrc

CMD ["/bin/bash"]
