package types

type DeployConfigTemplate struct {
	NativeTokenName                          string   `json:"nativeTokenName"`
	NativeTokenSymbol                        string   `json:"nativeTokenSymbol"`
	NativeTokenAddress                       string   `json:"nativeTokenAddress"`
	FinalSystemOwner                         string   `json:"finalSystemOwner"`
	SuperchainConfigGuardian                 string   `json:"superchainConfigGuardian"`
	L1StartingBlockTag                       string   `json:"l1StartingBlockTag,omitempty"`
	L1ChainID                                uint64   `json:"l1ChainId"`
	L2ChainID                                uint64   `json:"l2ChainId"`
	L2BlockTime                              uint64   `json:"l2BlockTime"`
	L1BlockTime                              uint64   `json:"l1BlockTime"`
	MaxSequencerDrift                        uint64   `json:"maxSequencerDrift"`
	SequencerWindowSize                      uint64   `json:"sequencerWindowSize"`
	ChannelTimeout                           uint64   `json:"channelTimeout"`
	P2pSequencerAddress                      string   `json:"p2pSequencerAddress"`
	BatchInboxAddress                        string   `json:"batchInboxAddress"`
	BatchSenderAddress                       string   `json:"batchSenderAddress"`
	L2OutputOracleSubmissionInterval         uint64   `json:"l2OutputOracleSubmissionInterval"`
	L2OutputOracleStartingTimestamp          uint64   `json:"l2OutputOracleStartingTimestamp"`
	L2OutputOracleStartingBlockNumber        uint64   `json:"l2OutputOracleStartingBlockNumber"`
	L2OutputOracleProposer                   string   `json:"l2OutputOracleProposer"`
	L2OutputOracleChallenger                 string   `json:"l2OutputOracleChallenger"`
	FinalizationPeriodSeconds                uint64   `json:"finalizationPeriodSeconds"`
	ProxyAdminOwner                          string   `json:"proxyAdminOwner"`
	BaseFeeVaultRecipient                    string   `json:"baseFeeVaultRecipient"`
	L1FeeVaultRecipient                      string   `json:"l1FeeVaultRecipient"`
	SequencerFeeVaultRecipient               string   `json:"sequencerFeeVaultRecipient"`
	BaseFeeVaultMinimumWithdrawalAmount      string   `json:"baseFeeVaultMinimumWithdrawalAmount"`
	L1FeeVaultMinimumWithdrawalAmount        string   `json:"l1FeeVaultMinimumWithdrawalAmount"`
	SequencerFeeVaultMinimumWithdrawalAmount string   `json:"sequencerFeeVaultMinimumWithdrawalAmount"`
	BaseFeeVaultWithdrawalNetwork            uint64   `json:"baseFeeVaultWithdrawalNetwork"`
	L1FeeVaultWithdrawalNetwork              uint64   `json:"l1FeeVaultWithdrawalNetwork"`
	SequencerFeeVaultWithdrawalNetwork       uint64   `json:"sequencerFeeVaultWithdrawalNetwork"`
	EnableGovernance                         bool     `json:"enableGovernance"`
	GovernanceTokenName                      string   `json:"governanceTokenName,omitempty"`
	GovernanceTokenSymbol                    string   `json:"governanceTokenSymbol,omitempty"`
	GovernanceTokenOwner                     string   `json:"governanceTokenOwner,omitempty"`
	L2GenesisBlockGasLimit                   string   `json:"l2GenesisBlockGasLimit"`
	L2GenesisBlockBaseFeePerGas              string   `json:"l2GenesisBlockBaseFeePerGas"`
	GasPriceOracleOverhead                   uint64   `json:"gasPriceOracleOverhead"`
	GasPriceOracleScalar                     uint64   `json:"gasPriceOracleScalar"`
	Eip1559Denominator                       uint64   `json:"eip1559Denominator"`
	Eip1559Elasticity                        uint64   `json:"eip1559Elasticity"`
	Eip1559DenominatorCanyon                 uint64   `json:"eip1559DenominatorCanyon"`
	L2GenesisRegolithTimeOffset              string   `json:"l2GenesisRegolithTimeOffset"`
	L2GenesisCanyonTimeOffset                string   `json:"l2GenesisCanyonTimeOffset"`
	L2GenesisDeltaTimeOffset                 string   `json:"l2GenesisDeltaTimeOffset"`
	L2GenesisEcotoneTimeOffset               string   `json:"l2GenesisEcotoneTimeOffset"`
	SystemConfigStartBlock                   uint64   `json:"systemConfigStartBlock"`
	RequiredProtocolVersion                  string   `json:"requiredProtocolVersion"`
	RecommendedProtocolVersion               string   `json:"recommendedProtocolVersion"`
	FaultGameAbsolutePrestate                string   `json:"faultGameAbsolutePrestate"`
	FaultGameMaxDepth                        uint64   `json:"faultGameMaxDepth"`
	FaultGameClockExtension                  uint64   `json:"faultGameClockExtension"`
	FaultGameMaxClockDuration                uint64   `json:"faultGameMaxClockDuration"`
	FaultGameGenesisBlock                    uint64   `json:"faultGameGenesisBlock"`
	FaultGameGenesisOutputRoot               string   `json:"faultGameGenesisOutputRoot"`
	FaultGameSplitDepth                      uint64   `json:"faultGameSplitDepth"`
	FaultGameWithdrawalDelay                 uint64   `json:"faultGameWithdrawalDelay"`
	PreimageOracleMinProposalSize            uint64   `json:"preimageOracleMinProposalSize"`
	PreimageOracleChallengePeriod            uint64   `json:"preimageOracleChallengePeriod"`
	ProofMaturityDelaySeconds                uint64   `json:"proofMaturityDelaySeconds"`
	DisputeGameFinalityDelaySeconds          uint64   `json:"disputeGameFinalityDelaySeconds"`
	RespectedGameType                        uint64   `json:"respectedGameType"`
	UseFaultProofs                           bool     `json:"useFaultProofs"`
	L1UsdcAddr                               string   `json:"l1UsdcAddr"`
	UsdcTokenName                            string   `json:"usdcTokenName"`
	NewPauser                                string   `json:"newPauser"`
	NewBlacklister                           string   `json:"newBlacklister"`
	MasterMinterOwner                        string   `json:"masterMinterOwner"`
	FiatTokenOwner                           string   `json:"fiatTokenOwner"`
	FactoryV2addr                            string   `json:"factoryV2addr"`
	NativeCurrencyLabelBytes                 []uint64 `json:"nativeCurrencyLabelBytes"`
	UniswapV3FactoryOwner                    string   `json:"uniswapV3FactoryOwner"`
	UniswapV3FactoryFee500                   uint64   `json:"uniswapV3FactoryFee500"`
	UniswapV3FactoryTickSpacing10            uint64   `json:"uniswapV3FactoryTickSpacing10"`
	UniswapV3FactoryFee3000                  uint64   `json:"uniswapV3FactoryFee3000"`
	UniswapV3FactoryTickSpacing60            uint64   `json:"uniswapV3FactoryTickSpacing60"`
	UniswapV3FactoryFee10000                 uint64   `json:"uniswapV3FactoryFee10000"`
	UniswapV3FactoryTickSpacing200           uint64   `json:"uniswapV3FactoryTickSpacing200"`
	UniswapV3FactoryFee100                   uint64   `json:"uniswapV3FactoryFee100"`
	UniswapV3FactoryTickSpacing1             uint64   `json:"uniswapV3FactoryTickSpacing1"`
	PairInitCodeHash                         string   `json:"pairInitCodeHash"`
	PoolInitCodeHash                         string   `json:"poolInitCodeHash"`
	UniversalRouterRewardsDistributor        string   `json:"universalRouterRewardsDistributor"`
}
