package thanos

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ethereum/go-ethereum/common"
)

const (
	//nolint:unused // used by injectMultiTokenPaymasterBytecode
	multiTokenPaymasterAddress = "0x4200000000000000000000000000000000000067"
)

// forgeArtifact represents the JSON structure of a forge build artifact.
type forgeArtifact struct {
	DeployedBytecode struct {
		Object string `json:"object"`
	} `json:"deployedBytecode"`
}

// injectMultiTokenPaymasterBytecode injects the updated MultiTokenPaymaster implementation
// bytecode into genesis.json at the predeploy code namespace address.
//
// MultiTokenPaymaster (0x4200...0067) is a Transparent Proxy. The implementation lives at
// the code namespace address (0xc0d3...0067). This function sets that implementation to the
// bytecode compiled with the v0.8 paymasterAndData offset fix ([52:72] instead of [20:40]).
//
// Prerequisite: forge build must have been run so that forge-artifacts exists.
//nolint:unused // called during L2 deployment orchestration
func injectMultiTokenPaymasterBytecode(genesisPath, deploymentPath string) error {
	data, err := os.ReadFile(genesisPath)
	if err != nil {
		return fmt.Errorf("failed to read genesis file: %w", err)
	}

	var genesis map[string]json.RawMessage
	if err := json.Unmarshal(data, &genesis); err != nil {
		return fmt.Errorf("failed to parse genesis JSON: %w", err)
	}

	var alloc map[string]json.RawMessage
	if err := json.Unmarshal(genesis["alloc"], &alloc); err != nil {
		return fmt.Errorf("failed to parse alloc section: %w", err)
	}

	// Detect alloc key format (with or without 0x prefix) from existing entries
	has0xPrefix := false
	for key := range alloc {
		if strings.HasPrefix(key, "0x") || strings.HasPrefix(key, "0X") {
			has0xPrefix = true
		}
		break
	}

	formatAddr := func(addr string) string {
		lower := strings.ToLower(addr)
		if !has0xPrefix {
			return strings.TrimPrefix(lower, "0x")
		}
		return lower
	}

	// Load deployedBytecode from forge-artifacts (generated by forge build)
	artifactPath := filepath.Join(
		deploymentPath,
		"tokamak-thanos", "packages", "tokamak", "contracts-bedrock",
		"forge-artifacts", "MultiTokenPaymaster.sol", "MultiTokenPaymaster.json",
	)
	implBytecode, err := loadForgeArtifactBytecode(artifactPath)
	if err != nil {
		return fmt.Errorf("failed to load MultiTokenPaymaster bytecode: %w", err)
	}

	// Set implementation at code namespace address
	// predeployToCodeNamespace is defined in drb_genesis.go (same package)
	proxyAddr := common.HexToAddress(multiTokenPaymasterAddress)
	codeAddr := predeployToCodeNamespace(proxyAddr)
	codeAddrKey := formatAddr(codeAddr.Hex())

	implEntry, err := json.Marshal(map[string]interface{}{
		"code":    implBytecode,
		"balance": "0x0",
	})
	if err != nil {
		return fmt.Errorf("failed to marshal implementation entry: %w", err)
	}
	alloc[codeAddrKey] = implEntry

	// Write back genesis.json
	allocJSON, err := json.Marshal(alloc)
	if err != nil {
		return fmt.Errorf("failed to marshal alloc: %w", err)
	}
	genesis["alloc"] = allocJSON

	output, err := json.MarshalIndent(genesis, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal genesis: %w", err)
	}

	fmt.Println("Injected MultiTokenPaymaster implementation (v0.8 paymasterAndData offset) into genesis code namespace at", codeAddr.Hex())
	return os.WriteFile(genesisPath, output, 0644)
}

// loadForgeArtifactBytecode reads a forge build artifact JSON and returns the deployedBytecode.
//nolint:unused // called by injectMultiTokenPaymasterBytecode
func loadForgeArtifactBytecode(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read artifact %s: %w", path, err)
	}

	var artifact forgeArtifact
	if err := json.Unmarshal(data, &artifact); err != nil {
		return "", fmt.Errorf("failed to parse artifact %s: %w", path, err)
	}

	if artifact.DeployedBytecode.Object == "" {
		return "", fmt.Errorf("empty deployedBytecode in %s", path)
	}

	return artifact.DeployedBytecode.Object, nil
}
